modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/ExtendedCrafting/issues"
    modId="extendedcrafting"
    version="${mod_version}"
    displayName="Extended Crafting"
    updateJSONURL="https://api.blakesmods.com/v2/mods/extendedcrafting/1.21/updates"
    displayURL="https://blakesmods.com/extended-crafting"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="SpitefulFox"
    description='''
    Adds some new ways to craft items, as well as extra crafting items and utilities.
    '''

    [[dependencies.extendedcrafting]]
        modId="neoforge"
        mandatory=true
        versionRange="[21.0.0-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.extendedcrafting]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.21,1.21.1)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.extendedcrafting]]
        modId="cucumber"
        mandatory=true
        versionRange="[7.0.4,)"
        ordering="NONE"
        side="BOTH"